/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": null,
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3208210256",
        "max": 0,
        "min": 0,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_782564964",
        "hidden": false,
        "id": "relation2196385364",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "commande_id",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "_clone_jRfQ",
        "name": "date_commande",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "_clone_72Z4",
        "max": null,
        "min": null,
        "name": "montant_total",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_t3xu",
        "max": 0,
        "min": 0,
        "name": "statut",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_bbod",
        "max": 0,
        "min": 0,
        "name": "adresse_domicile",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_Dext",
        "max": 0,
        "min": 0,
        "name": "mode_paiement",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "_pb_users_auth_",
        "hidden": false,
        "id": "_clone_tOs2",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "user_id",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_427234108",
        "hidden": false,
        "id": "_clone_ryZE",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "lunette_id",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_qTMv",
        "max": 0,
        "min": 0,
        "name": "nom_lunette",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_J3rH",
        "max": 0,
        "min": 0,
        "name": "forme",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_MapA",
        "max": 0,
        "min": 0,
        "name": "mode_creation",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_nBQ1",
        "max": 0,
        "min": 0,
        "name": "type_monture",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_g6m3",
        "max": 0,
        "min": 0,
        "name": "type_verre",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_3bch",
        "max": 0,
        "min": 0,
        "name": "taille",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_xmin",
        "max": 0,
        "min": 0,
        "name": "couleur_monture",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "_clone_kSoi",
        "max": 0,
        "min": 0,
        "name": "couleur_branches",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      }
    ],
    "id": "pbc_1235818745",
    "indexes": [],
    "listRule": null,
    "name": "Commandes_dun_utilisateur_connectee_a_ses_lunettes",
    "system": false,
    "type": "view",
    "updateRule": null,
    "viewQuery": "SELECT\n  (ROW_NUMBER() OVER()) AS id,\n\n  commande.id AS commande_id,\n  commande.created AS date_commande,\n  commande.montant_total,\n  commande.statut,\n  commande.adresse_domicile,\n  commande.mode_paiement,\n  commande.user AS user_id,\n  c_lunettes.lunette_id,\n  l.nom_creation AS nom_lunette,\n  l.forme,\n  l.mode_creation,\n  l.type_monture,\n  l.type_verre,\n  l.taille,\n  l.couleur_monture,\n  l.couleur_branches\nFROM commande\nLEFT JOIN commande_lunettes AS c_lunettes ON commande.id = c_lunettes.commande_id\nLEFT JOIN lunettes AS l ON c_lunettes.lunette_id = l.id",
    "viewRule": null
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_1235818745");

  return app.delete(collection);
})
